/*
 * プロダクト名：Sample
 *
 * APIの説明
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"api/handlers"

	"github.com/gin-gonic/gin"
)


type SampleAPI struct {
	handlers handlers.SampleAPIHandlers
}

func NewSampleAPI(handlers handlers.SampleAPIHandlers) SampleAPI {
	return SampleAPI{handlers: handlers}
}


// Post /sample
// サンプルPOSTリクエスト 
func (api *SampleAPI) PostSample(c *gin.Context) {
	api.handlers.PostSample(c)
}
