/*
 * プロダクト名：Sample
 *
 * APIの説明
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"api/handlers"

	"github.com/gin-gonic/gin"
)

type AuthenticationAPI struct {
}

// Post /login
// ログイン 
func (api *AuthenticationAPI) PostLogin(c *gin.Context) {
	handlers.PostLogin(c)
}

// Post /logout
// ログアウト 
func (api *AuthenticationAPI) PostLogout(c *gin.Context) {
	handlers.PostLogout(c)
}

// Post /refresh-token
// トークン再発行 
func (api *AuthenticationAPI) PostRefreshToken(c *gin.Context) {
	handlers.PostRefreshToken(c)
}

