/*
 * プロダクト名：Sample
 *
 * APIの説明
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostRefreshToken401Response struct {

	Error string `json:"error,omitempty"`
}
