/*
 * プロダクト名：Sample
 *
 * APIの説明
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthRequest struct {

	Uid string `json:"uid,omitempty" binding:"required"`

	Password string `json:"password,omitempty" binding:"required"`
}
