openapi: 3.0.0
info:
  title: プロダクト名：Sample
  description: APIの説明
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /login:
    post:
      tags:
        - Authentication
      x-go-tag: Authentication
      summary: ログイン
      operationId: PostLogin
      requestBody:
        description: ログインに必要なユーザー認証情報
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: jwt_access_token
                  refresh_token:
                    type: string
                    example: jwt_refresh_token
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid credentials
        '500':
          $ref: '#/components/responses/InternalServerError'
  /sample:
    post:
      tags:
        - Sample
      summary: サンプルPOSTリクエスト
      operationId: PostSample
      requestBody:
        description: サンプルリクエストパラメータ
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: リクエスト成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    AuthRequest:
      type: object
      properties:
        uid:
          type: string
          x-go-custom-tag: binding:"required"
        password:
          type: string
          x-go-custom-tag: binding:"required"
  responses:
    InternalServerError:
      description: サーバーエラー
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unexpected error
