version: "3"
networks:
  duu_go_network:
    driver: bridge
services:
  app:
    container_name: duu_go_app
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh
    networks:
      - duu_go_network
  mysql:
    container_name: duu_go_mysql
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - ./sh/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - duu_go_network
  redis:
    container_name: duu_go_redis
    image: redis:6.2.4
    ports:
      - 6379:6379
    networks:
      - duu_go_network