package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"api/ent"
	"api/resolver/model"
	"context"
	"fmt"
	"log"
	"strconv"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	entUsers, err := r.client.User.Query().All(ctx)
	if err != nil {
		log.Fatalf("failed querying Users: %v", err)
	}
	modelUsers := make([]*model.User, len(entUsers))
	for i, entUser := range entUsers {
		modelUsers[i] = &model.User{
			ID:    strconv.Itoa(entUser.ID),
			Name:  entUser.Name,
			Email: entUser.Email,
		}
	}
	return modelUsers, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
